//
//  DashboardInteractor.swift
//  GoogleTopHeadlines
//
//  Created by HalitG on 13.02.2021.
//  Copyright (c) 2021 HalitG. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol DashboardBusinessLogic
{
  func fetchData(searchKey: String)
}

protocol DashboardDataStore
{
  //var name: String { get set }
}

class DashboardInteractor: DashboardBusinessLogic, DashboardDataStore
{
  var presenter: DashboardPresentationLogic?
  //var name: String = ""
  
  // MARK: Do something
  
    func fetchData(searchKey: String)
  {
    let category: NewsCategory = .general
    loadData(category: category.rawValue, searchKey: searchKey)
  }
    
    
    func loadData(category: String, searchKey: String) {
        guard let url = NewsApi.urlForCategory(category: category, searchKey: searchKey) else {
            print("load data error")
            return
        }

        NewsApi.getArticles(url: url) { [weak self] (articles) in
            guard let articles = articles else { return }
            
            self?.presenter?.presentArticle(articles: articles)
        }
    }
}
