//
//  DashboardInteractor.swift
//  GoogleTopHeadlines
//
//  Created by HalitG on 13.02.2021.
//  Copyright (c) 2021 HalitG. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol DashboardBusinessLogic
{
  func doSomething(request: Dashboard.Something.Request)
}

protocol DashboardDataStore
{
  //var name: String { get set }
}

class DashboardInteractor: DashboardBusinessLogic, DashboardDataStore
{
  var presenter: DashboardPresentationLogic?
  var worker: DashboardWorker?
  //var name: String = ""
  
  // MARK: Do something
  
  func doSomething(request: Dashboard.Something.Request)
  {
    worker = DashboardWorker()
    worker?.doSomeWork()
    
    var category: NewsCategory = .general
    loadData(category.rawValue)
    
    let response = Dashboard.Something.Response()
    presenter?.presentSomething(response: response)
  }
    
    
    func loadData(_ category: String) {
        guard let url = NewsApi.urlForCategory(category) else {
            print("load data error")
            return
        }

        NewsApi.getArticles(url: url) { [weak self] (articles) in
            guard let articles = articles else { return }
            print(articles)
        }
    }
}
