//
//  DashboardModels.swift
//  GoogleTopHeadlines
//
//  Created by HalitG on 13.02.2021.
//  Copyright (c) 2021 HalitG. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

class newsArticle: NSObject {
    
    var headline: String?
    var desc: String?
    var author: String?
    var imageUrl: String?
    var postURL: String?
}
